### ISSUE TITLE
Ved innlasting av 2023-fil: Det har oppstått en feil - ('Error - 500: Number of passed names did not match number of header fields in the file.',).

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service#113]
Frå loggen:
> {
    "message": "Number of passed names did not match number of header fields in the file",
    "exc_info": 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/aiohttp_middlewares/error.py", line 210, in middleware\n    return await handler(request)\n  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py", line 954, in _iter\n    resp = await method()\n  File "/app/event_service/views/contestants.py", line 157, in post\n    result = await ContestantsService.create_contestants(\n  File "/app/event_service/services/contestants_service.py", line 233, in create_contestants\n    df = pd.read_csv(\n  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__\n    self._engine = self._make_engine(f, self.engine)\n  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine\n    return mapping[engine](f, **self.options)\n  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n  File "pandas/_libs/parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__\n  File "pandas/_libs/parsers.pyx", line 777, in pandas._libs.parsers.TextReader._get_header\nValueError: Number of passed names did not match number of header fields in the file',
    "severity": "ERROR",
    "serviceContext": {"service": "event-service"},
}

**Comment by stigbd** [comment]
Det var fleire feil her:
- Lagra med "," som separator. Denne skal vere ";" (semi-kolon). _Tiltak_: Endra til semi-kolon.
- Neste var at back-end forventer 2 "tittel-linjer", og disse blir ignorert. _Tiltak_: La til to linjer i toppen.
- Neste: "Usecols do not match columns, columns expected but not found: ['E-post', 'Idrettsnr']."
-- Forventar "E-post", som er ikkje lenger i fila. I staden fins "E-post lagleder" og "E-post påmelder". _Tiltak_: Endra "E-post påmelder" til "E-post".
-- Forventar "Idrettsnr". Denne er ikkje i fila. _Tiltak_: La til tom kolonne "Idrettsnr".

Då lot fila seg parse, men endte opp med blank skjerm med meldinga: "Got more than 8190 bytes (56431) when reading Status line is too long."
I url finner vi lang melding. Utdrag:
> Opprettet+659+av+761+deltakere.<br><br>Duplikater+(102):<br>-+contestant:+%7B%27first_name%27:+%27Felix+Misvær%27,+%27last_name%27:+%27Falck%27,+%27birth_date%27:+None,+%27gender%27:+%27M%27,+%27ageclass%2

Dette ser ikkje heilt rimeleg ut, og er nok pga ein bug i måten ein sjekkar for duplikater for når idrettsnr ikkje er oppgitt. 
Sjekken ser då etter contestant med samme fornavn og etternavn.

**Comment by stigbd** [comment]
Tiltak: Utfør betre validering av input-fil slik at det er mulig å gi meir fornuftig feilmeldinger til bruker.

**Comment by stigbd** [comment]
Vil bli fiksa i #114
