### ISSUE TITLE
GCP - innlasting av deltakere feiler

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#82]
user-service_1        | 172.23.0.5 [31/Jan/2022:19:46:52 +0000] "POST /authorize HTTP/1.1" 204 98 "-" "Python/3.9 
aiohttp/3.8.1"
event-service_1       | ERROR:aiohttp_middlewares.error:'utf-8' codec can't decode byte 0xe5 in position 1: invali
d continuation byte
event-service_1       | Traceback (most recent call last):
event-service_1       |   File "/usr/local/lib/python3.9/site-packages/aiohttp_middlewares/error.py", line 208, in
 middleware
event-service_1       |     return await handler(request)
event-service_1       |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 954, in
 _iter
event-service_1       |     resp = await method()
event-service_1       |   File "/app/event_service/views/contestants.py", line 152, in post
event-service_1       |     contestants = content.decode()
event-service_1       | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 1: invalid continuati
on byte
event-service_1       | 172.23.0.7 [31/Jan/2022:19:46:52 +0000] "POST /events/eec7c178-1d2d-4878-a532-5a9d05077e58
/contestants HTTP/1.1" 500 267 "-" "Python/3.9 aiohttp/3.8.1"
event-service-gui_1   | INFO:root:result - got response 500 - <ClientResponse(http://event-service:8080/events/eec
7c178-1d2d-4878-a532-5a9d05077e58/contestants) [500 Internal Server Error]>
event-service-gui_1   | <CIMultiDictProxy('Content-Type': 'application/json; charset=utf-8', 'Content-Length': '91
', 'Date': 'Mon, 31 Jan 2022 19:46:52 GMT', 'Server': 'Python/3.9 aiohttp/3.8.1')>
event-service-gui_1   | 
event-service-gui_1   | ERROR:root:create_contestants failed - 500 - {'detail': "'utf-8' codec can't decode byte 0
xe5 in position 1: invalid continuation byte"}
event-service-gui_1   | ERROR:root:Error: Error - 500: 'utf-8' codec can't decode byte 0xe5 in position 1: invalid
 continuation byte.
event-service-gui_1   | 79.161.109.194 [31/Jan/2022:19:46:52 +0000] "POST /contestants HTTP/1.1" 303 396 "http://3
4.88.91.136:8080/contestants?event_id=eec7c178-1d2d-4878-a532-5a9d05077e58&action=new_from_file&new_from_file=++La
st+inn+deltakere+fra+fil++" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chro
me/97.0.4692.99 Safari/537.36"

**Comment by heming-langrenn** [comment]
Denne er løst i frontend - ved å sette tegnsett.
